$(".aa").on('click',function(){ 
    $.ajax("https://ademolabakare.github.io/homepage/")
    .done(function(data){
        $(".seconed_side").html(data);
    });
  });
  $(".bb").on('click',function(){
    $.ajax("https://ademolabakare.github.io/french/")
    .done(function(data){
        $(".seconed_side").html(data);
    });
  });
  $(".cc").on('click',function(){
    $.ajax("https://ademolabakare.github.io/german/")
    .done(function(data){
        $(".seconed_side").html(data);
    });
  });
  $(".dd").on('click',function(){
     $.ajax("https://ademolabakare.github.io/homepage/")
    .done(function(data){
        $(".seconed_side").html(data);
    });
  });
  $(".ee").on('click',function(){
  $.ajax("https://ademolabakare.github.io/homepage/")
    .done(function(data){
        $(".seconed_side").html(data);
    });
  });
